In [1]:
from __future__ import print_function, unicode_literals, division
import pandas as pd
import numpy as np
# ! cut -d, -f1-4 /Users/markyashar/digital-wallet/paymo_input/batch_payment.csv_orig > /Users/markyashar/digital-wallet/paymo_input/batch_payment.csv
batchData = pd.read_csv("../paymo_input/batch_payment.csv", sep=', ')
batchData.time = pd.to_datetime(batchData.time,format="%Y-%m-%d %H:%M:%S")
batchData.head()

/Users/markyashar/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:5: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.

                 time    id1    id2  amount
0 2016-11-02 09:38:53  49466   6989   23.74
1 2016-11-02 09:38:53  52349   8552   37.10
2 2016-11-02 09:38:53  32639   2562   18.68
3 2016-11-02 09:38:53  15381  13167   20.92
4 2016-11-02 09:38:53  17052   6289   39.09

In [2]:
batchData.dtypes

time      datetime64[ns]
id1                int64
id2                int64
amount           float64
dtype: object

In [3]:
print(batchData.shape)
print(batchData.isnull().sum())
print(batchData.isnull().any())
print(batchData.count())
print(batchData.size)
print(batchData.info())

(3938360, 4)
time      0
id1       0
id2       0
amount    0
dtype: int64
time      False
id1       False
id2       False
amount    False
dtype: bool
time      3938360
id1       3938360
id2       3938360
amount    3938360
dtype: int64
15753440
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3938360 entries, 0 to 3938359
Data columns (total 4 columns):
time      datetime64[ns]
id1       int64
id2       int64
amount    float64
dtypes: datetime64[ns](1), float64(1), int64(2)
memory usage: 120.2 MB
None

In [4]:
(numRows,numColumns) = batchData.shape
print("Number of rows in batch_payment.csv: ", numRows)
print("Number of columns in batch_payment.csv: ", numColumns)
print("Number of users making payments in batch_payment.csv", batchData.id1.unique().shape)
print("Number of users receiving payments in batch_payment.csv", batchData.id2.unique().shape)
print("Number of unique times in the batch_payment.csv", batchData.time.unique().shape)

Number of rows in batch_payment.csv:  3938360
Number of columns in batch_payment.csv:  4
Number of users making payments in batch_payment.csv (77360,)
Number of users receiving payments in batch_payment.csv (77360,)
Number of unique times in the batch_payment.csv (630,)

In [5]:
# At the Unix command prompt, I did:
# cut -d, -f1-4 stream_payment.csv_orig > stream_payment.csv
streamData = pd.read_csv("../paymo_input/stream_payment.csv", sep=', ')
streamData.time = pd.to_datetime(streamData.time,format="%Y-%m-%d %H:%M:%S")
streamData.dtypes
streamData.head()

/Users/markyashar/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:3: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  app.launch_new_instance()

                 time    id1    id2  amount
0 2016-11-02 09:49:29  52575   1120   25.32
1 2016-11-02 09:49:29  47424   5995   19.45
2 2016-11-02 09:49:29  76352  64866   14.99
3 2016-11-02 09:49:29  20449   1552   13.48
4 2016-11-02 09:49:29  48676  19395   29.94

In [6]:
print(streamData.shape)
print(streamData.isnull().sum())
print(streamData.isnull().any())
print(streamData.count())
print(streamData.size)
print(streamData.info())

(3000000, 4)
time      0
id1       0
id2       0
amount    0
dtype: int64
time      False
id1       False
id2       False
amount    False
dtype: bool
time      3000000
id1       3000000
id2       3000000
amount    3000000
dtype: int64
12000000
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000000 entries, 0 to 2999999
Data columns (total 4 columns):
time      datetime64[ns]
id1       int64
id2       int64
amount    float64
dtypes: datetime64[ns](1), float64(1), int64(2)
memory usage: 91.6 MB
None

In [7]:
(numRows,numColumns) = streamData.shape
print("Number of rows in stream_payment.csv: ", numRows)
print("Number of columns in stream_payment.csv: ", numColumns)
print("Number of users making payments in stream_payment.csv", streamData.id1.unique().shape)
print("Number of users receiving payments in stream_payment.csv", streamData.id2.unique().shape)
print("Number of unique times in the stream_payment.csv", streamData.time.unique().shape)

Number of rows in stream_payment.csv:  3000000
Number of columns in stream_payment.csv:  4
Number of users making payments in stream_payment.csv (80538,)
Number of users receiving payments in stream_payment.csv (80611,)
Number of unique times in the stream_payment.csv (3003,)

In [8]:
streamData[streamData.duplicated(['id1','id2'], keep=False)].groupby(('id1','id2')).min().reset_index()

          id1    id2                time  amount
0           3   4820 2016-11-02 11:39:35   21.16
1           3   4821 2016-11-02 11:30:18   15.05
2           5   4730 2016-11-02 09:50:03    8.66
3           5   4920 2016-11-02 09:51:24   22.21
4           5   4921 2016-11-02 11:33:02   20.92
5           5  67513 2016-11-02 11:40:21    7.29
6           6  47026 2016-11-02 09:52:41   19.13
7           7      0 2016-11-02 09:59:43   28.44
8           7    138 2016-11-02 11:31:27   21.69
9           7   1220 2016-11-02 11:36:11   20.29
10          7   4982 2016-11-02 11:53:23   28.24
11          9      0 2016-11-02 09:52:20   18.75
12          9    498 2016-11-02 11:47:09   16.94
13          9   4736 2016-11-02 09:50:24    8.59
14          9   4837 2016-11-02 11:36:38   11.97
15          9   5203 2016-11-02 09:55:04   24.88
16         10   2990 2016-11-02 09:50:14    1.12
17         10   5209 2016-11-02 11:37:32   21.84
18         10   5298 2016-11-02 11:36:16   16.77
19         10  26779 2016-11-02 09:55:26   13.50
20         10  43998 2016-11-02 11:33:57   18.33
21         11   1071 2016-11-02 11:28:35   23.05
22         11   5234 2016-11-02 09:54:54   24.24
23         13   5289 2016-11-02 09:58:08   16.02
24         13   5329 2016-11-02 09:52:35   23.21
25         14   5391 2016-11-02 09:58:06   11.60
26         14   5439 2016-11-02 11:53:37   24.04
27         15  54457 2016-11-02 09:55:31   27.10
28         16   1044 2016-11-02 09:50:51    6.67
29         16   2682 2016-11-02 09:59:32   14.21
...       ...    ...                 ...     ...
267372  80427  64741 2016-11-02 12:09:56   16.76
267373  80429  16376 2016-11-02 12:08:22   29.25
267374  80430  12341 2016-11-02 12:09:28   23.68
267375  80432  20768 2016-11-02 12:09:42   28.45
267376  80433  34453 2016-11-02 12:09:09    9.04
267377  80434  27350 2016-11-02 12:09:11   18.23
267378  80436  41138 2016-11-02 12:10:21   20.43
267379  80439  40047 2016-11-02 12:10:09    4.09
267380  80448  11896 2016-11-02 12:09:30   14.72
267381  80451  58106 2016-11-02 12:09:35   29.03
267382  80463  70072 2016-11-02 12:08:56    7.34
267383  80467  33990 2016-11-02 12:08:53   15.32
267384  80468   9410 2016-11-02 12:10:02    7.63
267385  80472  41638 2016-11-02 12:09:25   27.06
267386  80482  62945 2016-11-02 12:10:36   11.79
267387  80483  13186 2016-11-02 12:10:12    2.88
267388  80487   8910 2016-11-02 12:09:49   16.41
267389  80488  21807 2016-11-02 12:09:44   13.83
267390  80491  11903 2016-11-02 12:09:41    9.66
267391  80493  66786 2016-11-02 12:09:40   14.27
267392  80499  60765 2016-11-02 12:09:55    8.11
267393  80508    143 2016-11-02 12:10:50   16.77
267394  80514  39451 2016-11-02 12:09:56   17.16
267395  80523  39566 2016-11-02 12:09:40   26.80
267396  80542  71077 2016-11-02 12:09:53   15.05
267397  80549  12785 2016-11-02 12:10:09   20.04
267398  80552   2889 2016-11-02 12:10:12   18.75
267399  80553  55019 2016-11-02 12:10:43   17.93
267400  80560  74670 2016-11-02 12:10:22    5.46
267401  80572  10875 2016-11-02 12:10:23    2.30

[267402 rows x 4 columns]

In [9]:
batch_streamData = batchData.merge(streamData,left_index=True,right_index=True)
batch_streamData.head(25)

,time_x,id1_x,id2_x,amount_x,time_y,id1_y,id2_y,amount_y
0,2016-11-02 09:38:53,49466,6989,23.74,2016-11-02 09:49:29,52575,1120,25.32
1,2016-11-02 09:38:53,52349,8552,37.10,2016-11-02 09:49:29,47424,5995,19.45
2,2016-11-02 09:38:53,32639,2562,18.68,2016-11-02 09:49:29,76352,64866,14.99
3,2016-11-02 09:38:53,15381,13167,20.92,2016-11-02 09:49:29,20449,1552,13.48
4,2016-11-02 09:38:53,17052,6289,39.09,2016-11-02 09:49:29,48676,19395,29.94
5,2016-11-02 09:38:53,54008,15138,21.74,2016-11-02 09:49:29,28505,45177,19.01
6,2016-11-02 09:38:53,74050,45140,36.92,2016-11-02 09:49:29,56157,16725,4.85
7,2016-11-02 09:38:53,46702,8034,32.07,2016-11-02 09:49:29,66543,8306,10.64
8,2016-11-02 09:38:53,41480,22688,3.19,2016-11-02 09:49:29,25036,24692,20.42
9,2016-11-02 09:38:53,47846,6067,14.96,2016-11-02 09:49:29,68290,66022,27.90
10,2016-11-02 09:38:53,54505,9696,20.00,2016-11-02 09:49:29,56275,5637,42.18
11,2016-11-02 09:38:53,18007,498,24.95,2016-11-02 09:49:29,23286,5448,45.92
12,2016-11-02 09:38:53,49174,6646,22.98,2016-11-02 09:49:29,70230,59830,19.33
13,2016-11-02 09:38:53,72459,72460,28.63,2016-11-02 09:49:29,42016,9013,19.19
14,2016-11-02 09:38:53,13238,5795,2.94,2016-11-02 09:49:29,50734,2942,29.20
15,2016-11-02 09:38:53,49509,74670,41.74,2016-11-02 09:49:29,39909,3940,31.20
16,2016-11-02 09:38:53,65203,76387,29.53,2016-11-02 09:49:29,63967,3197,38.09
17,2016-11-02 09:38:53,20711,5504,22.74,2016-11-02 09:49:29,8665,5524,15.45
18,2016-11-02 09:38:53,67795,23442,3.42,2016-11-02 09:49:29,20762,13233,25.06
19,2016-11-02 09:38:53,35494,3009,34.52,2016-11-02 09:49:29,6681,49196,19.75
20,2016-11-02 09:38:53,43424,7413,29.09,2016-11-02 09:49:29,33114,33106,17.77
21,2016-11-02 09:38:53,16965,52460,14.95,2016-11-02 09:49:29,34424,2844,20.76
22,2016-11-02 09:38:53,7032,34,8.66,2016-11-02 09:49:29,35149,24068,11.62
23,2016-11-02 09:38:53,32656,2562,8.28,2016-11-02 09:49:29,68884,26032,44.70
24,2016-11-02 09:38:53,77059,73447,21.97,2016-11-02 09:49:29,11102,3827,24.78

In [10]:
feature1_trusted = batch_streamData[(batch_streamData.id1_x==batch_streamData.id1_y) & (batch_streamData.id2_x==batch_streamData.id2_y)]
print(len(feature1_trusted))
trusted='trusted'
feature1_trusted=feature1_trusted.assign(trusted=trusted)
feature1_trusted.columns = ['' if x=='trusted' else x for x in feature1_trusted.columns]
feature1_trusted

12

,time_x,id1_x,id2_x,amount_x,time_y,id1_y,id2_y,amount_y,
348556,2016-11-02 09:45:13,4962,8393,38.79,2016-11-02 09:55:58,4962,8393,18.53,trusted
1091482,2016-11-02 09:48:31,60312,13535,32.49,2016-11-02 11:37:51,60312,13535,45.68,trusted
1146920,2016-11-02 09:48:32,67463,22697,41.91,2016-11-02 11:38:48,67463,22697,20.32,trusted
1449624,2016-11-02 09:48:38,37454,3401,28.32,2016-11-02 11:44:09,37454,3401,7.53,trusted
1925594,2016-11-02 09:48:48,55677,10306,16.87,2016-11-02 11:52:57,55677,10306,14.28,trusted
2054359,2016-11-02 09:48:51,66208,20452,28.32,2016-11-02 11:55:07,66208,20452,19.91,trusted
2304141,2016-11-02 09:48:56,51679,8286,14.08,2016-11-02 11:59:36,51679,8286,6.23,trusted
2462013,2016-11-02 09:48:59,75596,57282,30.09,2016-11-02 12:02:18,75596,57282,22.62,trusted
2488582,2016-11-02 09:48:59,69915,28641,25.46,2016-11-02 12:02:40,69915,28641,3.54,trusted
2496194,2016-11-02 09:49:00,8139,28535,36.94,2016-11-02 12:02:48,8139,28535,28.39,trusted
2566018,2016-11-02 09:49:01,40843,73193,27.54,2016-11-02 12:04:00,40843,73193,24.12,trusted
2656972,2016-11-02 09:49:03,61763,14987,37.54,2016-11-02 12:05:32,61763,14987,5.84,trusted

In [11]:
feature1_unverified = batch_streamData[(batch_streamData.id1_x != batch_streamData.id1_y) & (batch_streamData.id2_x != batch_streamData.id2_y)]
print(len(feature1_unverified))
unverified='unverified'
feature1_unverified=feature1_unverified.assign(unverified=unverified)
feature1_unverified.columns = ['' if x=='unverified' else x for x in feature1_unverified.columns]
feature1_unverified

2999454

,time_x,id1_x,id2_x,amount_x,time_y,id1_y,id2_y,amount_y,
0,2016-11-02 09:38:53,49466,6989,23.74,2016-11-02 09:49:29,52575,1120,25.32,unverified
1,2016-11-02 09:38:53,52349,8552,37.10,2016-11-02 09:49:29,47424,5995,19.45,unverified
2,2016-11-02 09:38:53,32639,2562,18.68,2016-11-02 09:49:29,76352,64866,14.99,unverified
3,2016-11-02 09:38:53,15381,13167,20.92,2016-11-02 09:49:29,20449,1552,13.48,unverified
4,2016-11-02 09:38:53,17052,6289,39.09,2016-11-02 09:49:29,48676,19395,29.94,unverified
5,2016-11-02 09:38:53,54008,15138,21.74,2016-11-02 09:49:29,28505,45177,19.01,unverified
6,2016-11-02 09:38:53,74050,45140,36.92,2016-11-02 09:49:29,56157,16725,4.85,unverified
7,2016-11-02 09:38:53,46702,8034,32.07,2016-11-02 09:49:29,66543,8306,10.64,unverified
8,2016-11-02 09:38:53,41480,22688,3.19,2016-11-02 09:49:29,25036,24692,20.42,unverified
9,2016-11-02 09:38:53,47846,6067,14.96,2016-11-02 09:49:29,68290,66022,27.90,unverified
10,2016-11-02 09:38:53,54505,9696,20.00,2016-11-02 09:49:29,56275,5637,42.18,unverified
11,2016-11-02 09:38:53,18007,498,24.95,2016-11-02 09:49:29,23286,5448,45.92,unverified
12,2016-11-02 09:38:53,49174,6646,22.98,2016-11-02 09:49:29,70230,59830,19.33,unverified
13,2016-11-02 09:38:53,72459,72460,28.63,2016-11-02 09:49:29,42016,9013,19.19,unverified
14,2016-11-02 09:38:53,13238,5795,2.94,2016-11-02 09:49:29,50734,2942,29.20,unverified
15,2016-11-02 09:38:53,49509,74670,41.74,2016-11-02 09:49:29,39909,3940,31.20,unverified
16,2016-11-02 09:38:53,65203,76387,29.53,2016-11-02 09:49:29,63967,3197,38.09,unverified
17,2016-11-02 09:38:53,20711,5504,22.74,2016-11-02 09:49:29,8665,5524,15.45,unverified
18,2016-11-02 09:38:53,67795,23442,3.42,2016-11-02 09:49:29,20762,13233,25.06,unverified
19,2016-11-02 09:38:53,35494,3009,34.52,2016-11-02 09:49:29,6681,49196,19.75,unverified
20,2016-11-02 09:38:53,43424,7413,29.09,2016-11-02 09:49:29,33114,33106,17.77,unverified
21,2016-11-02 09:38:53,16965,52460,14.95,2016-11-02 09:49:29,34424,2844,20.76,unverified
22,2016-11-02 09:38:53,7032,34,8.66,2016-11-02 09:49:29,35149,24068,11.62,unverified
23,2016-11-02 09:38:53,32656,2562,8.28,2016-11-02 09:49:29,68884,26032,44.70,unverified
24,2016-11-02 09:38:53,77059,73447,21.97,2016-11-02 09:49:29,11102,3827,24.78,unverified
25,2016-11-02 09:38:53,55755,10331,19.83,2016-11-02 09:49:29,36020,3081,17.78,unverified
26,2016-11-02 09:38:53,20640,23310,10.91,2016-11-02 09:49:29,12506,24675,18.82,unverified
27,2016-11-02 09:38:53,73785,43828,25.38,2016-11-02 09:49:29,66750,21442,22.46,unverified
28,2016-11-02 09:38:53,38721,3865,26.78,2016-11-02 09:49:29,42252,32471,36.48,unverified
29,2016-11-02 09:38:53,49425,4929,14.88,2016-11-02 09:49:29,31481,47752,23.37,unverified
...,...,...,...,...,...,...,...,...,...
2999970,2016-11-02 09:49:10,21088,11239,38.10,2016-11-02 12:11:09,13924,48063,22.61,unverified
2999971,2016-11-02 09:49:10,21831,7669,36.29,2016-11-02 12:11:09,49499,7015,8.41,unverified
2999972,2016-11-02 09:49:10,12529,175,42.91,2016-11-02 12:11:09,48080,5199,30.55,unverified
2999973,2016-11-02 09:49:10,602,5347,24.58,2016-11-02 12:11:09,60038,10096,16.07,unverified
2999974,2016-11-02 09:49:10,73470,42206,25.30,2016-11-02 12:11:09,54239,9298,17.82,unverified
2999975,2016-11-02 09:49:10,35912,10676,17.30,2016-11-02 12:11:09,20030,11303,1.45,unverified
2999976,2016-11-02 09:49:10,4384,39998,19.04,2016-11-02 12:11:09,63698,3832,17.26,unverified
2999977,2016-11-02 09:49:10,23193,1157,16.64,2016-11-02 12:11:09,60402,13925,21.62,unverified
2999978,2016-11-02 09:49:10,67852,23553,34.56,2016-11-02 12:11:09,70087,33400,37.02,unverified
2999979,2016-11-02 09:49:10,13331,6623,36.16,2016-11-02 12:11:09,74807,32430,13.70,unverified
2999980,2016-11-02 09:49:10,55216,10114,33.52,2016-11-02 12:11:09,37090,3031,7.26,unverified
2999981,2016-11-02 09:49:10,56707,16266,34.04,2016-11-02 12:11:09,5420,14,34.87,unverified
2999982,2016-11-02 09:49:10,27859,37306,27.09,2016-11-02 12:11:09,32159,26160,36.27,unverified
2999983,2016-11-02 09:49:10,1897,28152,13.54,2016-11-02 12:11:09,43330,22694,14.30,unverified
2999984,2016-11-02 09:49:10,19948,4723,36.36,2016-11-02 12:11:09,34483,2908,19.81,unverified
2999985,2016-11-02 09:49:10,39630,48175,21.85,2016-11-02 12:11:09,8808,6256,39.78,unverified
2999986,2016-11-02 09:49:10,10963,1498,19.24,2016-11-02 12:11:09,52559,80358,6.12,unverified
2999987,2016-11-02 09:49:10,68201,24265,17.40,2016-11-02 12:11:09,34122,17053,23.41,unverified
2999988,2016-11-02 09:49:10,58598,12166,28.22,2016-11-02 12:11:09,54153,26631,42.41,unverified
2999989,2016-11-02 09:49:10,69451,27239,23.87,2016-11-02 12:11:09,9030,59,15.88,unverified
2999990,2016-11-02 09:49:10,68706,72459,19.62,2016-11-02 12:11:09,46268,73642,42.05,unverified
2999991,2016-11-02 09:49:10,31190,2473,19.97,2016-11-02 12:11:09,35774,11765,8.05,unverified
2999992,2016-11-02 09:49:10,75486,56179,9.87,2016-11-02 12:11:09,33093,38399,27.54,unverified
2999993,2016-11-02 09:49:10,5180,8,5.81,2016-11-02 12:11:09,39776,4282,22.30,unverified
2999994,2016-11-02 09:49:10,74701,49761,15.25,2016-11-02 12:11:09,14352,9977,23.96,unverified
2999995,2016-11-02 09:49:10,66265,16189,33.34,2016-11-02 12:11:09,67485,6199,31.03,unverified
2999996,2016-11-02 09:49:10,47956,15,30.89,2016-11-02 12:11:09,67501,22803,24.32,unverified
2999997,2016-11-02 09:49:10,16174,7811,8.95,2016-11-02 12:11:09,25628,46349,23.89,unverified
2999998,2016-11-02 09:49:10,45777,5527,35.47,2016-11-02 12:11:09,60835,13929,24.61,unverified
2999999,2016-11-02 09:49:10,43144,23263,47.69,2016-11-02 12:11:09,41563,17545,31.06,unverified

In [12]:
# frames=[feature1_unverified,feature1_trusted]
# result_feature1 = pd.concat(frames)
result_feature1 = feature1_unverified.append(feature1_trusted)
result_feature1.sort_index(inplace=True)
result_feature1

,time_x,id1_x,id2_x,amount_x,time_y,id1_y,id2_y,amount_y,
0,2016-11-02 09:38:53,49466,6989,23.74,2016-11-02 09:49:29,52575,1120,25.32,unverified
1,2016-11-02 09:38:53,52349,8552,37.10,2016-11-02 09:49:29,47424,5995,19.45,unverified
2,2016-11-02 09:38:53,32639,2562,18.68,2016-11-02 09:49:29,76352,64866,14.99,unverified
3,2016-11-02 09:38:53,15381,13167,20.92,2016-11-02 09:49:29,20449,1552,13.48,unverified
4,2016-11-02 09:38:53,17052,6289,39.09,2016-11-02 09:49:29,48676,19395,29.94,unverified
5,2016-11-02 09:38:53,54008,15138,21.74,2016-11-02 09:49:29,28505,45177,19.01,unverified
6,2016-11-02 09:38:53,74050,45140,36.92,2016-11-02 09:49:29,56157,16725,4.85,unverified
7,2016-11-02 09:38:53,46702,8034,32.07,2016-11-02 09:49:29,66543,8306,10.64,unverified
8,2016-11-02 09:38:53,41480,22688,3.19,2016-11-02 09:49:29,25036,24692,20.42,unverified
9,2016-11-02 09:38:53,47846,6067,14.96,2016-11-02 09:49:29,68290,66022,27.90,unverified
10,2016-11-02 09:38:53,54505,9696,20.00,2016-11-02 09:49:29,56275,5637,42.18,unverified
11,2016-11-02 09:38:53,18007,498,24.95,2016-11-02 09:49:29,23286,5448,45.92,unverified
12,2016-11-02 09:38:53,49174,6646,22.98,2016-11-02 09:49:29,70230,59830,19.33,unverified
13,2016-11-02 09:38:53,72459,72460,28.63,2016-11-02 09:49:29,42016,9013,19.19,unverified
14,2016-11-02 09:38:53,13238,5795,2.94,2016-11-02 09:49:29,50734,2942,29.20,unverified
15,2016-11-02 09:38:53,49509,74670,41.74,2016-11-02 09:49:29,39909,3940,31.20,unverified
16,2016-11-02 09:38:53,65203,76387,29.53,2016-11-02 09:49:29,63967,3197,38.09,unverified
17,2016-11-02 09:38:53,20711,5504,22.74,2016-11-02 09:49:29,8665,5524,15.45,unverified
18,2016-11-02 09:38:53,67795,23442,3.42,2016-11-02 09:49:29,20762,13233,25.06,unverified
19,2016-11-02 09:38:53,35494,3009,34.52,2016-11-02 09:49:29,6681,49196,19.75,unverified
20,2016-11-02 09:38:53,43424,7413,29.09,2016-11-02 09:49:29,33114,33106,17.77,unverified
21,2016-11-02 09:38:53,16965,52460,14.95,2016-11-02 09:49:29,34424,2844,20.76,unverified
22,2016-11-02 09:38:53,7032,34,8.66,2016-11-02 09:49:29,35149,24068,11.62,unverified
23,2016-11-02 09:38:53,32656,2562,8.28,2016-11-02 09:49:29,68884,26032,44.70,unverified
24,2016-11-02 09:38:53,77059,73447,21.97,2016-11-02 09:49:29,11102,3827,24.78,unverified
25,2016-11-02 09:38:53,55755,10331,19.83,2016-11-02 09:49:29,36020,3081,17.78,unverified
26,2016-11-02 09:38:53,20640,23310,10.91,2016-11-02 09:49:29,12506,24675,18.82,unverified
27,2016-11-02 09:38:53,73785,43828,25.38,2016-11-02 09:49:29,66750,21442,22.46,unverified
28,2016-11-02 09:38:53,38721,3865,26.78,2016-11-02 09:49:29,42252,32471,36.48,unverified
29,2016-11-02 09:38:53,49425,4929,14.88,2016-11-02 09:49:29,31481,47752,23.37,unverified
...,...,...,...,...,...,...,...,...,...
2999970,2016-11-02 09:49:10,21088,11239,38.10,2016-11-02 12:11:09,13924,48063,22.61,unverified
2999971,2016-11-02 09:49:10,21831,7669,36.29,2016-11-02 12:11:09,49499,7015,8.41,unverified
2999972,2016-11-02 09:49:10,12529,175,42.91,2016-11-02 12:11:09,48080,5199,30.55,unverified
2999973,2016-11-02 09:49:10,602,5347,24.58,2016-11-02 12:11:09,60038,10096,16.07,unverified
2999974,2016-11-02 09:49:10,73470,42206,25.30,2016-11-02 12:11:09,54239,9298,17.82,unverified
2999975,2016-11-02 09:49:10,35912,10676,17.30,2016-11-02 12:11:09,20030,11303,1.45,unverified
2999976,2016-11-02 09:49:10,4384,39998,19.04,2016-11-02 12:11:09,63698,3832,17.26,unverified
2999977,2016-11-02 09:49:10,23193,1157,16.64,2016-11-02 12:11:09,60402,13925,21.62,unverified
2999978,2016-11-02 09:49:10,67852,23553,34.56,2016-11-02 12:11:09,70087,33400,37.02,unverified
2999979,2016-11-02 09:49:10,13331,6623,36.16,2016-11-02 12:11:09,74807,32430,13.70,unverified
2999980,2016-11-02 09:49:10,55216,10114,33.52,2016-11-02 12:11:09,37090,3031,7.26,unverified
2999981,2016-11-02 09:49:10,56707,16266,34.04,2016-11-02 12:11:09,5420,14,34.87,unverified
2999982,2016-11-02 09:49:10,27859,37306,27.09,2016-11-02 12:11:09,32159,26160,36.27,unverified
2999983,2016-11-02 09:49:10,1897,28152,13.54,2016-11-02 12:11:09,43330,22694,14.30,unverified
2999984,2016-11-02 09:49:10,19948,4723,36.36,2016-11-02 12:11:09,34483,2908,19.81,unverified
2999985,2016-11-02 09:49:10,39630,48175,21.85,2016-11-02 12:11:09,8808,6256,39.78,unverified
2999986,2016-11-02 09:49:10,10963,1498,19.24,2016-11-02 12:11:09,52559,80358,6.12,unverified
2999987,2016-11-02 09:49:10,68201,24265,17.40,2016-11-02 12:11:09,34122,17053,23.41,unverified
2999988,2016-11-02 09:49:10,58598,12166,28.22,2016-11-02 12:11:09,54153,26631,42.41,unverified
2999989,2016-11-02 09:49:10,69451,27239,23.87,2016-11-02 12:11:09,9030,59,15.88,unverified
2999990,2016-11-02 09:49:10,68706,72459,19.62,2016-11-02 12:11:09,46268,73642,42.05,unverified
2999991,2016-11-02 09:49:10,31190,2473,19.97,2016-11-02 12:11:09,35774,11765,8.05,unverified
2999992,2016-11-02 09:49:10,75486,56179,9.87,2016-11-02 12:11:09,33093,38399,27.54,unverified
2999993,2016-11-02 09:49:10,5180,8,5.81,2016-11-02 12:11:09,39776,4282,22.30,unverified
2999994,2016-11-02 09:49:10,74701,49761,15.25,2016-11-02 12:11:09,14352,9977,23.96,unverified
2999995,2016-11-02 09:49:10,66265,16189,33.34,2016-11-02 12:11:09,67485,6199,31.03,unverified
2999996,2016-11-02 09:49:10,47956,15,30.89,2016-11-02 12:11:09,67501,22803,24.32,unverified
2999997,2016-11-02 09:49:10,16174,7811,8.95,2016-11-02 12:11:09,25628,46349,23.89,unverified
2999998,2016-11-02 09:49:10,45777,5527,35.47,2016-11-02 12:11:09,60835,13929,24.61,unverified
2999999,2016-11-02 09:49:10,43144,23263,47.69,2016-11-02 12:11:09,41563,17545,31.06,unverified

In [ ]:
result_feature1.loc[2566018]   # this is just a test

time_x      2016-11-02 09:49:01
id1_x                     40843
id2_x                     73193
amount_x                  27.54
time_y      2016-11-02 12:04:00
id1_y                     40843
id2_y                     73193
amount_y                  24.12
                        trusted
Name: 2566018, dtype: object

In [ ]:
result_feature1.columns = ['status' if x=='' else x for x in result_feature1.columns]
# print(result_feature1.status.to_string(index=False))
# results_feature1 = result_feature1.status.to_string(index=False).to_csv('../paymo_output/output1.txt', header=False, index=False, mode= 'a')
results_feature1 = result_feature1.status.to_string(index=False)
# results_feature1.to_csv(r'../paymo_output/output1.txt', header=None, index=None)

In [ ]:
import os, csv
# results_feature1.to_csv(r'../paymo_output/output1.txt', header=None, index=None, mode='a')
# np.savetxt(r'../paymo_output/output1.txt',results_feature1.values)
# results_feature1.to_csv('../paymo_output/output1.txt', header=False, index=False, mode= 'a')
# with open('../paymo_output/output1.txt', 'a') as f:
#    results_feature1.to_csv(f, line_terminator=',', index=False, header=False)
# print(results_feature1)
# output = '/Users/markyashar/digital-wallet/paymo_output/output1.txt'
# for item in results_feature1:
#   output.write("%s\n" % item)
# for item in results_feature1:
#     print>>output, item
# import pickle

# pickle.dump(results_feature1.encode('utf-8'), output)
# print(results_feature1.to_csv(output, header=False, index=False))
# WriteFile = True # Write CSV file if true - useful for testing


# CSVFileName = "output1.txt"
# CSVfile = open(os.path.join('/Users/markyashar/digital-wallet/paymo_output/', CSVFileName), 'w')
# results_feature1.encode("ascii").writer('../paymo_output/output1.txt', header=False, index=False, mode= 'a')
results_feature1.encode('ascii','replace')

In [28]:
feature2_trusted = batch_streamData[(batch_streamData.id1_x == batch_streamData.id2_y) 
                                    & (batch_streamData.id2_x != batch_streamData.id2_y)] 
                                    # & (batch_streamData.id2_x == batch_streamData.id1_y)] # & 
                                     #      (batch_streamData.id1_x != batch_streamData.id2_y)]
                                   #  or ((batch_streamData.id1_x == batch_streamData.id2_y) & 
                                   #     (batch_streamData.id2_x == batch_streamData.id2_y))]
print(len(feature2_trusted))
trusted='trusted'
feature2_trusted=feature2_trusted.assign(trusted=trusted)
feature2_trusted.columns = ['' if x=='trusted' else x for x in feature2_trusted.columns]
feature2_trusted

177

,time_x,id1_x,id2_x,amount_x,time_y,id1_y,id2_y,amount_y,
29024,2016-11-02 09:39:49,1672,394,28.48,2016-11-02 09:49:58,41491,1672,38.65,trusted
155122,2016-11-02 09:42:50,408,545,10.05,2016-11-02 09:52:22,17337,408,2.22,trusted
225714,2016-11-02 09:43:54,33476,8391,13.65,2016-11-02 09:53:42,35633,33476,27.17,trusted
274019,2016-11-02 09:44:29,8009,5949,32.77,2016-11-02 09:54:40,51173,8009,23.58,trusted
282504,2016-11-02 09:44:34,2882,1357,31.24,2016-11-02 09:54:48,12410,2882,29.20,trusted
308900,2016-11-02 09:44:51,9889,54805,26.06,2016-11-02 09:55:16,2250,9889,17.95,trusted
310545,2016-11-02 09:44:52,8309,11030,12.79,2016-11-02 09:55:18,28337,8309,18.25,trusted
319047,2016-11-02 09:44:57,32278,55347,22.50,2016-11-02 09:55:28,27330,32278,21.61,trusted
375996,2016-11-02 09:45:27,6129,5514,21.04,2016-11-02 09:56:41,40894,6129,33.49,trusted
406751,2016-11-02 09:45:41,2662,25000,33.21,2016-11-02 09:57:12,33041,2662,40.84,trusted
424624,2016-11-02 09:45:50,4387,11027,14.04,2016-11-02 09:57:31,40000,4387,2.62,trusted
442471,2016-11-02 09:45:57,21269,9196,35.76,2016-11-02 09:57:51,40965,21269,13.11,trusted
448909,2016-11-02 09:46:00,21306,11506,7.37,2016-11-02 09:57:55,66680,21306,21.13,trusted
459037,2016-11-02 09:46:04,10327,36898,27.99,2016-11-02 09:58:07,55730,10327,29.57,trusted
472223,2016-11-02 09:46:09,74,9548,11.72,2016-11-02 09:58:21,9524,74,12.13,trusted
472735,2016-11-02 09:46:10,38414,15724,21.07,2016-11-02 09:58:22,72716,38414,15.03,trusted
495197,2016-11-02 09:46:18,12,1826,9.73,2016-11-02 09:58:42,40398,12,32.41,trusted
510521,2016-11-02 09:46:24,22,18172,6.92,2016-11-02 09:59:06,5860,22,34.62,trusted
515778,2016-11-02 09:46:26,5217,112,19.13,2016-11-02 09:59:10,32138,5217,12.13,trusted
536470,2016-11-02 09:46:34,4540,1874,21.98,2016-11-02 09:59:28,11579,4540,23.32,trusted
539637,2016-11-02 09:46:35,394,2011,10.40,2016-11-02 09:59:32,23296,394,21.68,trusted
546644,2016-11-02 09:46:37,2208,1924,16.50,2016-11-02 09:59:39,29727,2208,30.11,trusted
547270,2016-11-02 09:46:37,13130,10649,34.16,2016-11-02 09:59:39,53435,13130,25.02,trusted
571763,2016-11-02 09:46:45,11896,24116,30.25,2016-11-02 11:28:37,75447,11896,23.14,trusted
578308,2016-11-02 09:46:47,34,7149,21.08,2016-11-02 11:28:46,7072,34,19.43,trusted
591397,2016-11-02 09:46:52,34,6863,13.79,2016-11-02 11:29:00,6985,34,31.61,trusted
593529,2016-11-02 09:46:52,1181,5114,3.73,2016-11-02 11:29:01,14835,1181,17.10,trusted
594187,2016-11-02 09:46:52,5049,7924,6.45,2016-11-02 11:29:03,18616,5049,32.74,trusted
605226,2016-11-02 09:46:56,23,5934,10.03,2016-11-02 11:29:14,5974,23,7.55,trusted
610685,2016-11-02 09:46:58,18762,8981,19.83,2016-11-02 11:29:21,65027,18762,12.16,trusted
...,...,...,...,...,...,...,...,...,...
1119010,2016-11-02 09:48:32,10114,14187,24.37,2016-11-02 11:38:21,55214,10114,11.09,trusted
1152830,2016-11-02 09:48:32,4012,18288,21.37,2016-11-02 11:38:57,8976,4012,5.97,trusted
1162607,2016-11-02 09:48:32,263,5041,19.37,2016-11-02 11:39:07,3340,263,28.34,trusted
1206235,2016-11-02 09:48:33,6068,25,17.71,2016-11-02 11:39:50,66568,6068,18.83,trusted
1311718,2016-11-02 09:48:35,574,2270,9.77,2016-11-02 11:41:40,34120,574,15.37,trusted
1481774,2016-11-02 09:48:39,64689,65793,22.95,2016-11-02 11:44:43,8155,64689,33.83,trusted
1501226,2016-11-02 09:48:39,62645,15741,23.54,2016-11-02 11:45:09,54836,62645,27.93,trusted
1513287,2016-11-02 09:48:40,6356,11268,38.90,2016-11-02 11:45:22,36263,6356,16.95,trusted
1744759,2016-11-02 09:48:44,28332,27336,40.01,2016-11-02 11:49:31,69791,28332,16.66,trusted
1976469,2016-11-02 09:48:49,5294,20366,18.83,2016-11-02 11:53:46,44818,5294,22.63,trusted
1983663,2016-11-02 09:48:49,8423,33868,9.32,2016-11-02 11:53:51,33861,8423,18.64,trusted
2075547,2016-11-02 09:48:51,10706,408,23.63,2016-11-02 11:55:32,8573,10706,13.89,trusted
2096449,2016-11-02 09:48:51,206,10746,29.28,2016-11-02 11:55:57,13418,206,13.18,trusted
2153342,2016-11-02 09:48:53,20186,3681,21.95,2016-11-02 11:56:55,62486,20186,12.81,trusted
2186519,2016-11-02 09:48:53,4445,18475,36.81,2016-11-02 11:57:40,40142,4445,14.08,trusted
2224578,2016-11-02 09:48:54,10913,13302,28.37,2016-11-02 11:58:15,3803,10913,25.15,trusted
2245788,2016-11-02 09:48:54,4406,40066,9.04,2016-11-02 11:58:39,25554,4406,22.05,trusted
2259455,2016-11-02 09:48:55,9998,8314,31.27,2016-11-02 11:58:54,7898,9998,24.38,trusted
2322590,2016-11-02 09:48:56,14486,13362,6.84,2016-11-02 11:59:59,46679,14486,3.41,trusted
2344417,2016-11-02 09:48:57,13665,2031,21.53,2016-11-02 12:00:19,60520,13665,4.77,trusted
2431766,2016-11-02 09:48:58,12336,171,17.28,2016-11-02 12:01:41,79521,12336,28.96,trusted
2488520,2016-11-02 09:48:59,12071,24776,16.51,2016-11-02 12:02:40,9920,12071,12.89,trusted
2578091,2016-11-02 09:49:01,2507,20438,25.21,2016-11-02 12:04:12,18280,2507,22.61,trusted
2765485,2016-11-02 09:49:05,14631,16239,48.05,2016-11-02 12:07:19,61401,14631,28.36,trusted
2784028,2016-11-02 09:49:05,488,16504,27.16,2016-11-02 12:07:34,17983,488,23.88,trusted
2804244,2016-11-02 09:49:06,5952,1439,31.40,2016-11-02 12:07:56,43283,5952,33.94,trusted
2931470,2016-11-02 09:49:08,3879,37180,27.14,2016-11-02 12:09:58,25996,3879,18.38,trusted
2949189,2016-11-02 09:49:09,20565,1273,41.61,2016-11-02 12:10:13,39685,20565,34.63,trusted
2954270,2016-11-02 09:49:09,72606,76987,46.28,2016-11-02 12:10:19,76987,72606,31.18,trusted
2991984,2016-11-02 09:49:10,17051,398,35.16,2016-11-02 12:11:02,46071,17051,21.43,trusted

In [29]:
feature2_unverified = batch_streamData[(batch_streamData.id1_x != batch_streamData.id1_y) & (batch_streamData.id2_x != batch_streamData.id2_y)]
print(len(feature2_unverified))
unverified='unverified'
feature2_unverified=feature2_unverified.assign(unverified=unverified)
feature2_unverified.columns = ['' if x=='unverified' else x for x in feature2_unverified.columns]
feature2_unverified

2999454

,time_x,id1_x,id2_x,amount_x,time_y,id1_y,id2_y,amount_y,
0,2016-11-02 09:38:53,49466,6989,23.74,2016-11-02 09:49:29,52575,1120,25.32,unverified
1,2016-11-02 09:38:53,52349,8552,37.10,2016-11-02 09:49:29,47424,5995,19.45,unverified
2,2016-11-02 09:38:53,32639,2562,18.68,2016-11-02 09:49:29,76352,64866,14.99,unverified
3,2016-11-02 09:38:53,15381,13167,20.92,2016-11-02 09:49:29,20449,1552,13.48,unverified
4,2016-11-02 09:38:53,17052,6289,39.09,2016-11-02 09:49:29,48676,19395,29.94,unverified
5,2016-11-02 09:38:53,54008,15138,21.74,2016-11-02 09:49:29,28505,45177,19.01,unverified
6,2016-11-02 09:38:53,74050,45140,36.92,2016-11-02 09:49:29,56157,16725,4.85,unverified
7,2016-11-02 09:38:53,46702,8034,32.07,2016-11-02 09:49:29,66543,8306,10.64,unverified
8,2016-11-02 09:38:53,41480,22688,3.19,2016-11-02 09:49:29,25036,24692,20.42,unverified
9,2016-11-02 09:38:53,47846,6067,14.96,2016-11-02 09:49:29,68290,66022,27.90,unverified
10,2016-11-02 09:38:53,54505,9696,20.00,2016-11-02 09:49:29,56275,5637,42.18,unverified
11,2016-11-02 09:38:53,18007,498,24.95,2016-11-02 09:49:29,23286,5448,45.92,unverified
12,2016-11-02 09:38:53,49174,6646,22.98,2016-11-02 09:49:29,70230,59830,19.33,unverified
13,2016-11-02 09:38:53,72459,72460,28.63,2016-11-02 09:49:29,42016,9013,19.19,unverified
14,2016-11-02 09:38:53,13238,5795,2.94,2016-11-02 09:49:29,50734,2942,29.20,unverified
15,2016-11-02 09:38:53,49509,74670,41.74,2016-11-02 09:49:29,39909,3940,31.20,unverified
16,2016-11-02 09:38:53,65203,76387,29.53,2016-11-02 09:49:29,63967,3197,38.09,unverified
17,2016-11-02 09:38:53,20711,5504,22.74,2016-11-02 09:49:29,8665,5524,15.45,unverified
18,2016-11-02 09:38:53,67795,23442,3.42,2016-11-02 09:49:29,20762,13233,25.06,unverified
19,2016-11-02 09:38:53,35494,3009,34.52,2016-11-02 09:49:29,6681,49196,19.75,unverified
20,2016-11-02 09:38:53,43424,7413,29.09,2016-11-02 09:49:29,33114,33106,17.77,unverified
21,2016-11-02 09:38:53,16965,52460,14.95,2016-11-02 09:49:29,34424,2844,20.76,unverified
22,2016-11-02 09:38:53,7032,34,8.66,2016-11-02 09:49:29,35149,24068,11.62,unverified
23,2016-11-02 09:38:53,32656,2562,8.28,2016-11-02 09:49:29,68884,26032,44.70,unverified
24,2016-11-02 09:38:53,77059,73447,21.97,2016-11-02 09:49:29,11102,3827,24.78,unverified
25,2016-11-02 09:38:53,55755,10331,19.83,2016-11-02 09:49:29,36020,3081,17.78,unverified
26,2016-11-02 09:38:53,20640,23310,10.91,2016-11-02 09:49:29,12506,24675,18.82,unverified
27,2016-11-02 09:38:53,73785,43828,25.38,2016-11-02 09:49:29,66750,21442,22.46,unverified
28,2016-11-02 09:38:53,38721,3865,26.78,2016-11-02 09:49:29,42252,32471,36.48,unverified
29,2016-11-02 09:38:53,49425,4929,14.88,2016-11-02 09:49:29,31481,47752,23.37,unverified
...,...,...,...,...,...,...,...,...,...
2999970,2016-11-02 09:49:10,21088,11239,38.10,2016-11-02 12:11:09,13924,48063,22.61,unverified
2999971,2016-11-02 09:49:10,21831,7669,36.29,2016-11-02 12:11:09,49499,7015,8.41,unverified
2999972,2016-11-02 09:49:10,12529,175,42.91,2016-11-02 12:11:09,48080,5199,30.55,unverified
2999973,2016-11-02 09:49:10,602,5347,24.58,2016-11-02 12:11:09,60038,10096,16.07,unverified
2999974,2016-11-02 09:49:10,73470,42206,25.30,2016-11-02 12:11:09,54239,9298,17.82,unverified
2999975,2016-11-02 09:49:10,35912,10676,17.30,2016-11-02 12:11:09,20030,11303,1.45,unverified
2999976,2016-11-02 09:49:10,4384,39998,19.04,2016-11-02 12:11:09,63698,3832,17.26,unverified
2999977,2016-11-02 09:49:10,23193,1157,16.64,2016-11-02 12:11:09,60402,13925,21.62,unverified
2999978,2016-11-02 09:49:10,67852,23553,34.56,2016-11-02 12:11:09,70087,33400,37.02,unverified
2999979,2016-11-02 09:49:10,13331,6623,36.16,2016-11-02 12:11:09,74807,32430,13.70,unverified
2999980,2016-11-02 09:49:10,55216,10114,33.52,2016-11-02 12:11:09,37090,3031,7.26,unverified
2999981,2016-11-02 09:49:10,56707,16266,34.04,2016-11-02 12:11:09,5420,14,34.87,unverified
2999982,2016-11-02 09:49:10,27859,37306,27.09,2016-11-02 12:11:09,32159,26160,36.27,unverified
2999983,2016-11-02 09:49:10,1897,28152,13.54,2016-11-02 12:11:09,43330,22694,14.30,unverified
2999984,2016-11-02 09:49:10,19948,4723,36.36,2016-11-02 12:11:09,34483,2908,19.81,unverified
2999985,2016-11-02 09:49:10,39630,48175,21.85,2016-11-02 12:11:09,8808,6256,39.78,unverified
2999986,2016-11-02 09:49:10,10963,1498,19.24,2016-11-02 12:11:09,52559,80358,6.12,unverified
2999987,2016-11-02 09:49:10,68201,24265,17.40,2016-11-02 12:11:09,34122,17053,23.41,unverified
2999988,2016-11-02 09:49:10,58598,12166,28.22,2016-11-02 12:11:09,54153,26631,42.41,unverified
2999989,2016-11-02 09:49:10,69451,27239,23.87,2016-11-02 12:11:09,9030,59,15.88,unverified
2999990,2016-11-02 09:49:10,68706,72459,19.62,2016-11-02 12:11:09,46268,73642,42.05,unverified
2999991,2016-11-02 09:49:10,31190,2473,19.97,2016-11-02 12:11:09,35774,11765,8.05,unverified
2999992,2016-11-02 09:49:10,75486,56179,9.87,2016-11-02 12:11:09,33093,38399,27.54,unverified
2999993,2016-11-02 09:49:10,5180,8,5.81,2016-11-02 12:11:09,39776,4282,22.30,unverified
2999994,2016-11-02 09:49:10,74701,49761,15.25,2016-11-02 12:11:09,14352,9977,23.96,unverified
2999995,2016-11-02 09:49:10,66265,16189,33.34,2016-11-02 12:11:09,67485,6199,31.03,unverified
2999996,2016-11-02 09:49:10,47956,15,30.89,2016-11-02 12:11:09,67501,22803,24.32,unverified
2999997,2016-11-02 09:49:10,16174,7811,8.95,2016-11-02 12:11:09,25628,46349,23.89,unverified
2999998,2016-11-02 09:49:10,45777,5527,35.47,2016-11-02 12:11:09,60835,13929,24.61,unverified
2999999,2016-11-02 09:49:10,43144,23263,47.69,2016-11-02 12:11:09,41563,17545,31.06,unverified

In [30]:
result_feature2 = feature2_unverified.append(feature2_trusted)
result_feature2.sort_index(inplace=True)
result_feature2

,time_x,id1_x,id2_x,amount_x,time_y,id1_y,id2_y,amount_y,
0,2016-11-02 09:38:53,49466,6989,23.74,2016-11-02 09:49:29,52575,1120,25.32,unverified
1,2016-11-02 09:38:53,52349,8552,37.10,2016-11-02 09:49:29,47424,5995,19.45,unverified
2,2016-11-02 09:38:53,32639,2562,18.68,2016-11-02 09:49:29,76352,64866,14.99,unverified
3,2016-11-02 09:38:53,15381,13167,20.92,2016-11-02 09:49:29,20449,1552,13.48,unverified
4,2016-11-02 09:38:53,17052,6289,39.09,2016-11-02 09:49:29,48676,19395,29.94,unverified
5,2016-11-02 09:38:53,54008,15138,21.74,2016-11-02 09:49:29,28505,45177,19.01,unverified
6,2016-11-02 09:38:53,74050,45140,36.92,2016-11-02 09:49:29,56157,16725,4.85,unverified
7,2016-11-02 09:38:53,46702,8034,32.07,2016-11-02 09:49:29,66543,8306,10.64,unverified
8,2016-11-02 09:38:53,41480,22688,3.19,2016-11-02 09:49:29,25036,24692,20.42,unverified
9,2016-11-02 09:38:53,47846,6067,14.96,2016-11-02 09:49:29,68290,66022,27.90,unverified
10,2016-11-02 09:38:53,54505,9696,20.00,2016-11-02 09:49:29,56275,5637,42.18,unverified
11,2016-11-02 09:38:53,18007,498,24.95,2016-11-02 09:49:29,23286,5448,45.92,unverified
12,2016-11-02 09:38:53,49174,6646,22.98,2016-11-02 09:49:29,70230,59830,19.33,unverified
13,2016-11-02 09:38:53,72459,72460,28.63,2016-11-02 09:49:29,42016,9013,19.19,unverified
14,2016-11-02 09:38:53,13238,5795,2.94,2016-11-02 09:49:29,50734,2942,29.20,unverified
15,2016-11-02 09:38:53,49509,74670,41.74,2016-11-02 09:49:29,39909,3940,31.20,unverified
16,2016-11-02 09:38:53,65203,76387,29.53,2016-11-02 09:49:29,63967,3197,38.09,unverified
17,2016-11-02 09:38:53,20711,5504,22.74,2016-11-02 09:49:29,8665,5524,15.45,unverified
18,2016-11-02 09:38:53,67795,23442,3.42,2016-11-02 09:49:29,20762,13233,25.06,unverified
19,2016-11-02 09:38:53,35494,3009,34.52,2016-11-02 09:49:29,6681,49196,19.75,unverified
20,2016-11-02 09:38:53,43424,7413,29.09,2016-11-02 09:49:29,33114,33106,17.77,unverified
21,2016-11-02 09:38:53,16965,52460,14.95,2016-11-02 09:49:29,34424,2844,20.76,unverified
22,2016-11-02 09:38:53,7032,34,8.66,2016-11-02 09:49:29,35149,24068,11.62,unverified
23,2016-11-02 09:38:53,32656,2562,8.28,2016-11-02 09:49:29,68884,26032,44.70,unverified
24,2016-11-02 09:38:53,77059,73447,21.97,2016-11-02 09:49:29,11102,3827,24.78,unverified
25,2016-11-02 09:38:53,55755,10331,19.83,2016-11-02 09:49:29,36020,3081,17.78,unverified
26,2016-11-02 09:38:53,20640,23310,10.91,2016-11-02 09:49:29,12506,24675,18.82,unverified
27,2016-11-02 09:38:53,73785,43828,25.38,2016-11-02 09:49:29,66750,21442,22.46,unverified
28,2016-11-02 09:38:53,38721,3865,26.78,2016-11-02 09:49:29,42252,32471,36.48,unverified
29,2016-11-02 09:38:53,49425,4929,14.88,2016-11-02 09:49:29,31481,47752,23.37,unverified
...,...,...,...,...,...,...,...,...,...
2999970,2016-11-02 09:49:10,21088,11239,38.10,2016-11-02 12:11:09,13924,48063,22.61,unverified
2999971,2016-11-02 09:49:10,21831,7669,36.29,2016-11-02 12:11:09,49499,7015,8.41,unverified
2999972,2016-11-02 09:49:10,12529,175,42.91,2016-11-02 12:11:09,48080,5199,30.55,unverified
2999973,2016-11-02 09:49:10,602,5347,24.58,2016-11-02 12:11:09,60038,10096,16.07,unverified
2999974,2016-11-02 09:49:10,73470,42206,25.30,2016-11-02 12:11:09,54239,9298,17.82,unverified
2999975,2016-11-02 09:49:10,35912,10676,17.30,2016-11-02 12:11:09,20030,11303,1.45,unverified
2999976,2016-11-02 09:49:10,4384,39998,19.04,2016-11-02 12:11:09,63698,3832,17.26,unverified
2999977,2016-11-02 09:49:10,23193,1157,16.64,2016-11-02 12:11:09,60402,13925,21.62,unverified
2999978,2016-11-02 09:49:10,67852,23553,34.56,2016-11-02 12:11:09,70087,33400,37.02,unverified
2999979,2016-11-02 09:49:10,13331,6623,36.16,2016-11-02 12:11:09,74807,32430,13.70,unverified
2999980,2016-11-02 09:49:10,55216,10114,33.52,2016-11-02 12:11:09,37090,3031,7.26,unverified
2999981,2016-11-02 09:49:10,56707,16266,34.04,2016-11-02 12:11:09,5420,14,34.87,unverified
2999982,2016-11-02 09:49:10,27859,37306,27.09,2016-11-02 12:11:09,32159,26160,36.27,unverified
2999983,2016-11-02 09:49:10,1897,28152,13.54,2016-11-02 12:11:09,43330,22694,14.30,unverified
2999984,2016-11-02 09:49:10,19948,4723,36.36,2016-11-02 12:11:09,34483,2908,19.81,unverified
2999985,2016-11-02 09:49:10,39630,48175,21.85,2016-11-02 12:11:09,8808,6256,39.78,unverified
2999986,2016-11-02 09:49:10,10963,1498,19.24,2016-11-02 12:11:09,52559,80358,6.12,unverified
2999987,2016-11-02 09:49:10,68201,24265,17.40,2016-11-02 12:11:09,34122,17053,23.41,unverified
2999988,2016-11-02 09:49:10,58598,12166,28.22,2016-11-02 12:11:09,54153,26631,42.41,unverified
2999989,2016-11-02 09:49:10,69451,27239,23.87,2016-11-02 12:11:09,9030,59,15.88,unverified
2999990,2016-11-02 09:49:10,68706,72459,19.62,2016-11-02 12:11:09,46268,73642,42.05,unverified
2999991,2016-11-02 09:49:10,31190,2473,19.97,2016-11-02 12:11:09,35774,11765,8.05,unverified
2999992,2016-11-02 09:49:10,75486,56179,9.87,2016-11-02 12:11:09,33093,38399,27.54,unverified
2999993,2016-11-02 09:49:10,5180,8,5.81,2016-11-02 12:11:09,39776,4282,22.30,unverified
2999994,2016-11-02 09:49:10,74701,49761,15.25,2016-11-02 12:11:09,14352,9977,23.96,unverified
2999995,2016-11-02 09:49:10,66265,16189,33.34,2016-11-02 12:11:09,67485,6199,31.03,unverified
2999996,2016-11-02 09:49:10,47956,15,30.89,2016-11-02 12:11:09,67501,22803,24.32,unverified
2999997,2016-11-02 09:49:10,16174,7811,8.95,2016-11-02 12:11:09,25628,46349,23.89,unverified
2999998,2016-11-02 09:49:10,45777,5527,35.47,2016-11-02 12:11:09,60835,13929,24.61,unverified
2999999,2016-11-02 09:49:10,43144,23263,47.69,2016-11-02 12:11:09,41563,17545,31.06,unverified

In [31]:
result_feature2.columns = ['status' if x=='' else x for x in result_feature2.columns]
results_feature2 = result_feature2.status.to_string(index=False)
results_feature1.encode('ascii','replace')
output2 = '/Users/markyashar/digital-wallet/paymo_output/output2.txt'
with open(output2, 'w') as f:
    for s in results_feature2:
        f.write(s)